# Generated by Django 5.0.4 on 2024-05-26 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comp', '0003_comp_theme_randommatching_ismatched_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='randommatching',
            name='person',
        ),
    ]
