# Generated by Django 5.0.4 on 2024-05-26 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicuser',
            name='email',
            field=models.CharField(default='email@gmail.com', max_length=50),
        ),
        migrations.AlterField(
            model_name='basicuser',
            name='img',
            field=models.TextField(default='https://teamkerbellbucket.s3.ap-northeast-2.amazonaws.com/default_profile.jpeg'),
        ),
        migrations.AlterField(
            model_name='basicuser',
            name='phone',
            field=models.CharField(default='010-0000-0000', max_length=50),
        ),
    ]
